// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package hanariu

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/Discorder20/raw-h/pkg/hanariu"

type CheckboxBosons struct {
	Error bool
	Attrs hanariu.Attrs
}

var checkboxStyles = hanariu.Boson{
	"default": "checkbox-default",
	"noerror": "checkbox-noerror",
	"error":   "checkbox-error",
}

func Checkbox(props *CheckboxBosons) templ.Component {
	attrs := make(hanariu.Attrs)
	for k, v := range props.Attrs {
		attrs[k] = v
	}
	attrs["type"] = "checkbox"
	return hanariu.CreateComponent("input", getCheckboxClasses(props.Error), attrs, true)
}

func getCheckboxClasses(err bool) string {
	var classes = checkboxStyles["default"] + " "
	if err {
		classes += checkboxStyles["error"]
	} else {
		classes += checkboxStyles["noerror"]
	}
	return classes
}

var _ = templruntime.GeneratedTemplate
