// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package hanariu

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import hanariu "github.com/Discorder20/raw-h/pkg/hanariu"

type IconHeroBosons struct {
	Size        string `default:"md"`
	Color       string `default:"primary"`
	Outline     bool
	Transparent bool
	Noborder    bool
	Square      bool
	ViewBox     string `default:"0 0 32 32"`
	Attrs       hanariu.Attrs
}

var iconHeroStyles = hanariu.Boson{
	"default":     "iconhero-default",
	"icon":        "iconhero-icon",
	"iconOutline": "iconhero-iconoutline",
	"transparent": "iconhero-transparent",
}

var iconHeroColorStyles = hanariu.Boson{
	"current":   "iconhero-color-current",
	"primary":   "iconhero-color-primary",
	"secondary": "iconhero-color-secondary",
	"warning":   "iconhero-color-warning",
	"danger":    "iconhero-color-danger",
	"success":   "iconhero-color-success",
	"info":      "iconhero-color-info",
}

var iconHeroColorBgStyles = hanariu.Boson{
	"current":   "iconhero-colorbg-current",
	"primary":   "iconhero-colorbg-primary",
	"secondary": "iconhero-colorbg-secondary",
	"warning":   "iconhero-colorbg-warning",
	"danger":    "iconhero-colorbg-danger",
	"success":   "iconhero-colorbg-success",
	"info":      "iconhero-colorbg-info",
}

var iconHeroColorBorderStyles = hanariu.Boson{
	"current":   "iconhero-colorborder-current",
	"primary":   "iconhero-colorborder-primary",
	"secondary": "iconhero-colorborder-secondary",
	"warning":   "iconhero-colorborder-warning",
	"danger":    "iconhero-colorborder-danger",
	"success":   "iconhero-colorborder-success",
	"info":      "iconhero-colorborder-info",
}

var iconHeroOutlineStyles = hanariu.Boson{
	"current":   "iconhero-outline-current",
	"primary":   "iconhero-outline-primary",
	"secondary": "iconhero-outline-secondary",
	"warning":   "iconhero-outline-warning",
	"danger":    "iconhero-outline-danger",
	"success":   "iconhero-outline-success",
	"info":      "iconhero-outline-info",
}

var iconHeroOutlineBgStyles = hanariu.Boson{
	"current":   "iconhero-outlinebg-current",
	"primary":   "iconhero-outlinebg-primary",
	"secondary": "iconhero-outlinebg-secondary",
	"warning":   "iconhero-outlinebg-warning",
	"danger":    "iconhero-outlinebg-danger",
	"success":   "iconhero-outlinebg-success",
	"info":      "iconhero-outlinebg-info",
}

var iconHeroOutlineBorderStyles = hanariu.Boson{
	"current":   "iconhero-outlineborder-current",
	"primary":   "iconhero-outlineborder-primary",
	"secondary": "iconhero-outlineborder-secondary",
	"warning":   "iconhero-outlineborder-warning",
	"danger":    "iconhero-outlineborder-danger",
	"success":   "iconhero-outlineborder-success",
	"info":      "iconhero-outlineborder-info",
}

var iconHeroBorderStyles = hanariu.Boson{
	"xs":      "iconhero-border-xs",
	"sm":      "iconhero-border-sm",
	"md":      "iconhero-border-md",
	"lg":      "iconhero-border-lg",
	"xl":      "iconhero-border-xl",
	"outline": "iconhero-border-outline",
	"border":  "iconhero-border-border",
	"full":    "iconhero-border-full",
	"square":  "iconhero-border-square",
}

var iconHeroSizeStyles = hanariu.Boson{
	"full": "iconhero-size-full",
	"xs":   "iconhero-size-xs",
	"sm":   "iconhero-size-sm",
	"md":   "iconhero-size-md",
	"lg":   "iconhero-size-lg",
	"xl":   "iconhero-size-xl",
}

var iconHeroOutlineSizeStyles = hanariu.Boson{
	"full": "iconhero-outlinesize-full",
	"xs":   "iconhero-outlinesize-xs",
	"sm":   "iconhero-outlinesize-sm",
	"md":   "iconhero-outlinesize-md",
	"lg":   "iconhero-outlinesize-lg",
	"xl":   "iconhero-outlinesize-xl",
}

func IconHero(props *IconHeroBosons) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var2 = []any{getIconHeroDivClasses(props.Size, props.Color, props.Outline, props.Transparent, props.Noborder, props.Square)}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/hanariu/protons/iconHero.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 = []any{getIconHeroSpanClasses(props.Outline)}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var4...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<span class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var4).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/hanariu/protons/iconHero.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var6 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = getIconHero(props).Render(templ.WithChildren(ctx, templ_7745c5c3_Var6), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</span></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func getIconHeroDivClasses(size string, color string, outline bool, transparent bool, noborder bool, square bool) string {
	propsSize := hanariu.GetTagDefault("Size", size, IconHeroBosons{})
	propsColor := hanariu.GetTagDefault("Color", color, IconHeroBosons{})
	var classes = iconHeroStyles["default"] + " " + iconHeroColorStyles[propsColor]
	if outline {
		classes += " " + iconHeroOutlineSizeStyles[propsSize] + " " + iconHeroOutlineStyles[propsColor] + " " + iconHeroBorderStyles["border"]
	} else {
		classes += " " + iconHeroSizeStyles[propsSize] + " " + iconHeroColorStyles[propsColor] + " " + iconHeroBorderStyles["outline"] + " " + iconHeroBorderStyles[propsSize]
	}

	if !noborder {
		if square {
			classes += " " + iconHeroBorderStyles["square"]
		} else {
			classes += " " + iconHeroBorderStyles["full"]
		}
		if outline {
			classes += " " + iconHeroOutlineBorderStyles[propsColor]

		} else {
			classes += " " + iconHeroColorBorderStyles[propsColor]
		}
	}

	if transparent {
		classes += " " + iconHeroStyles["transparent"]
	} else {
		if outline {
			classes += " " + iconHeroOutlineBgStyles[propsColor]
		} else {
			classes += " " + iconHeroColorBgStyles[propsColor]
		}
	}

	return classes
}

func getIconHeroSpanClasses(outline bool) string {
	if outline {
		return iconHeroStyles["iconOutline"]
	} else {
		return iconHeroStyles["icon"]
	}
}

func getIconHero(props *IconHeroBosons) templ.Component {
	classes := getIconHeroIconClasses()
	attrs := make(hanariu.Attrs)
	attrs["viewbox"] = hanariu.GetTagDefault("ViewBox", props.ViewBox, IconButtonBosons{})
	return hanariu.CreateComponent("svg", classes, attrs, false)
}

func getIconHeroIconClasses() string {
	var classes = "fill-current w-full h-full"
	return classes
}

var _ = templruntime.GeneratedTemplate
