// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package hanariu

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/Discorder20/raw-h/pkg/hanariu"

type RadioBosons struct {
	Error bool
	Attrs hanariu.Attrs
}

var radioStyles = hanariu.Boson{
	"default": "radio-default",
	"noerror": "radio-noerror",
	"error":   "radio-error",
}

func Radio(props *RadioBosons) templ.Component {
	attrs := make(hanariu.Attrs)
	for k, v := range props.Attrs {
		attrs[k] = v
	}
	attrs["type"] = "radio"
	return hanariu.CreateComponent("input", getRadioClasses(props.Error), attrs, true)
}

func getRadioClasses(err bool) string {
	var classes = radioStyles["default"] + " "
	if err {
		classes += radioStyles["error"]
	} else {
		classes += radioStyles["noerror"]
	}
	return classes
}

var _ = templruntime.GeneratedTemplate
