// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package hanariu

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import hanariu "github.com/Discorder20/raw-h/pkg/hanariu"

type SpinnerBosons struct {
	Size  string `default:"md"`
	Color string `default:"primary"`
}

var spinnerSizeStyles = hanariu.Boson{
	"xs": "spinner-size-xs",
	"sm": "spinner-size-sm",
	"md": "spinner-size-md",
	"lg": "spinner-size-lg",
	"xl": "spinner-size-xl",
}

var spinnerColorStyles = hanariu.Boson{
	"primary":   "spinner-color-primary",
	"secondary": "spinner-color-secondary",
	"warning":   "spinner-color-warning",
	"danger":    "spinner-color-danger",
	"success":   "spinner-color-success",
	"info":      "spinner-color-info",
}

var spinnerStyles = hanariu.Boson{
	"spinner": "spinner-spinner",
}

func Spinner(props *SpinnerBosons) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var2 = []any{getSpinnerClasses(props.Size, props.Color)}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/hanariu/protons/spinner.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" class=\"spinner-1067\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func getSpinnerClasses(size, color string) string {
	spinnerColor := hanariu.GetTagDefault("Color", color, SpinnerBosons{})
	spinnerSize := hanariu.GetTagDefault("Size", size, SpinnerBosons{})
	return hanariu.CreateClasses("Size", spinnerSize, SpinnerBosons{}, spinnerSizeStyles) + " " + hanariu.CreateClasses("Color", spinnerColor, SpinnerBosons{}, spinnerColorStyles) + " " + spinnerStyles["spinner"]
}

var _ = templruntime.GeneratedTemplate
