// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package hanariu

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/Discorder20/raw-h/pkg/hanariu"
	protons "github.com/Discorder20/raw-h/pkg/hanariu/protons"
)

type ButtonBosons struct {
	Size     string `default:"md"`
	Color    string `default:"primary"`
	Type     string `default:"button"`
	Tag      string `default:"button"`
	Rounded  bool
	Outline  bool
	Light    bool
	Disabled bool
	Icononly bool
	Full     bool
	Reverse  bool
	Title    string `default:"Button"`
	Attrs    hanariu.Attrs
}

var buttonStyles = hanariu.Boson{
	"default":           "button-default",
	"active":            "button-active",
	"borderTransparent": "button-bordertransparent",
	"shadow":            "button-shadow",
	"outline":           "button-outline",
	"rounded":           "button-rounded",
	"square":            "button-square",
	"squarexs":          "button-squarexs",
	"reverse":           "button-reverse",
	"full":              "button-full",
	"disabled":          "button-disabled",
}

var buttonColorStyles = hanariu.Boson{
	"primary":   "button-color-primary",
	"secondary": "button-color-secondary",
	"warning":   "button-color-warning",
	"danger":    "button-color-danger",
	"success":   "button-color-success",
	"info":      "button-color-info",
}

var buttonColorDisabledStyles = hanariu.Boson{
	"primary":   "button-colordisabled-primary",
	"secondary": "button-colordisabled-secondary",
	"warning":   "button-colordisabled-warning",
	"danger":    "button-colordisabled-danger",
	"success":   "button-colordisabled-success",
	"info":      "button-colordisabled-info",
}

var buttonLightStyles = hanariu.Boson{
	"primary":   "button-light-primary",
	"secondary": "button-light-secondary",
	"warning":   "button-light-warning",
	"danger":    "button-light-danger",
	"success":   "button-light-success",
	"info":      "button-light-info",
}

var buttonLightDisabledStyles = hanariu.Boson{
	"primary":   "button-lightdisabled-primary",
	"secondary": "button-lightdisabled-secondary",
	"warning":   "button-lightdisabled-warning",
	"danger":    "button-lightdisabled-danger",
	"success":   "button-lightdisabled-success",
	"info":      "button-lightdisabled-info",
}

var buttonOutlineStyles = hanariu.Boson{
	"primary":   "button-outline-primary",
	"secondary": "button-outline-secondary",
	"warning":   "button-outline-warning",
	"danger":    "button-outline-danger",
	"success":   "button-outline-success",
	"info":      "button-outline-info",
}

var buttonOutlineDisabledStyles = hanariu.Boson{
	"primary":   "button-outlinedisabled-primary",
	"secondary": "button-outlinedisabled-secondary",
	"warning":   "button-outlinedisabled-warning",
	"danger":    "button-outlinedisabled-danger",
	"success":   "button-outlinedisabled-success",
	"info":      "button-outlinedisabled-info",
}

var buttonSizeStyles = hanariu.Boson{
	"xs": "button-size-xs",
	"sm": "button-size-sm",
	"md": "button-size-md",
	"lg": "button-size-lg",
	"xl": "button-size-xl",
}

var buttonSizeIconStyles = hanariu.Boson{
	"xs": "button-sizeicon-xs",
	"sm": "button-sizeicon-sm",
	"md": "button-sizeicon-md",
	"lg": "button-sizeicon-lg",
	"xl": "button-sizeicon-xl",
}

func (attr *ButtonBosons) makeButtonAttrs() {
	attrs := make(hanariu.Attrs)
	for k, v := range attr.Attrs {
		attrs[k] = v
	}
	attr.Attrs = attrs
}

func (prop *ButtonBosons) addButtonAttr(k, v string) {
	prop.Attrs[k] = v
}

func ButtonButton(props *ButtonBosons) templ.Component {
	props.Size = hanariu.GetTagDefault("Size", props.Size, ButtonBosons{})
	props.Color = hanariu.GetTagDefault("Color", props.Color, ButtonBosons{})
	props.Type = hanariu.GetTagDefault("Type", props.Type, ButtonBosons{})
	props.Title = hanariu.GetTagDefault("Title", props.Title, ButtonBosons{})
	props.makeButtonAttrs()
	props.addButtonAttr("type", props.Type)
	props.addButtonAttr("aria-label", props.Title)
	if props.Disabled && props.Type == "button" {
		props.addButtonAttr("disabled", "")
	}
	props.Tag = hanariu.GetTagDefault("Tag", props.Tag, ButtonBosons{})
	classes := getButtonClasses(props)
	return hanariu.CreateComponent(props.Tag, classes, props.Attrs, false)
}

func Button(props *ButtonBosons) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(props.Title)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/hanariu/atoms/button.templ`, Line: 138, Col: 15}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = ButtonButton(props).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func ButtonIcon(props *ButtonBosons) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var5 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Var6 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
				templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
				if !templ_7745c5c3_IsBuffer {
					defer func() {
						templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err == nil {
							templ_7745c5c3_Err = templ_7745c5c3_BufErr
						}
					}()
				}
				ctx = templ.InitializeContext(ctx)
				templ_7745c5c3_Err = templ_7745c5c3_Var4.Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				return nil
			})
			templ_7745c5c3_Err = protons.IconButton(&protons.IconButtonBosons{Size: props.Size, Reverse: props.Reverse, Icononly: props.Icononly}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var6), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !props.Icononly {
				var templ_7745c5c3_Var7 string
				templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(props.Title)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/hanariu/atoms/button.templ`, Line: 148, Col: 16}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			return nil
		})
		templ_7745c5c3_Err = ButtonButton(props).Render(templ.WithChildren(ctx, templ_7745c5c3_Var5), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func getButtonClasses(props *ButtonBosons) string {
	var buttonClasses = buttonStyles["default"]
	if !props.Icononly && props.Reverse {
		buttonClasses += " " + buttonStyles["reverse"]
	}
	if props.Icononly {
		buttonClasses += " " + buttonSizeIconStyles[props.Size]
	} else {
		buttonClasses += " " + buttonSizeStyles[props.Size]
	}

	if props.Outline {
		if props.Disabled {
			buttonClasses += " " + buttonStyles["disabled"] + " " + buttonOutlineDisabledStyles[props.Color] + " " + buttonStyles["borderTransparent"]
		} else {
			buttonClasses += " " + buttonStyles["active"] + " " + buttonStyles["outline"] + " " + buttonOutlineStyles[props.Color]
		}
	} else if props.Light {
		if props.Disabled {
			buttonClasses += " " + buttonStyles["disabled"] + " " + buttonLightDisabledStyles[props.Color] + " " + buttonStyles["borderTransparent"]
		} else {
			buttonClasses += " " + buttonStyles["active"] + " " + buttonStyles["borderTransparent"] + " " + buttonLightStyles[props.Color]
		}
	} else {
		if props.Disabled {
			buttonClasses += " " + buttonStyles["disabled"] + " " + buttonColorDisabledStyles[props.Color]
		} else {
			buttonClasses += " " + buttonStyles["active"] + " " + buttonStyles["borderTransparent"] + " " + buttonStyles["shadow"] + " " + buttonColorStyles[props.Color]
		}
	}

	if props.Rounded {
		buttonClasses += " " + buttonStyles["rounded"]
	} else {
		if props.Size == "xs" {
			buttonClasses += " " + buttonStyles["squarexs"]
		} else {
			buttonClasses += " " + buttonStyles["square"]
		}
	}

	if props.Full {
		buttonClasses += " " + buttonStyles["full"]
	}

	return buttonClasses
}

var _ = templruntime.GeneratedTemplate
