// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package hanariu

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/Discorder20/raw-h/pkg/hanariu"

type FormFieldBosons struct {
	Template string `default:"vertical"`
	Attrs    hanariu.Attrs
}

var formFieldStyles = hanariu.Boson{
	"default": "formfield-default",
}

var formFieldTemplateStyles = hanariu.Boson{
	"vertical":   "formfield-template-vertical",
	"horizontal": "formfield-template-horizontal",
	"radio":      "formfield-template-radio",
	"toggle":     "formfield-template-toggle",
	"checkbox":   "formfield-template-checkbox",
}

func FormField(props *FormFieldBosons) templ.Component {
	classes := getFormFieldClasses(props.Template)
	return hanariu.CreateComponent("div", classes, props.Attrs, false)
}

func getFormFieldClasses(template string) string {
	temp := hanariu.GetTagDefault("Template", template, FormFieldBosons{})
	return formFieldStyles["default"] + " " + formFieldTemplateStyles[temp]
}

var _ = templruntime.GeneratedTemplate
