// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package hanariu

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/Discorder20/raw-h/pkg/hanariu"

type FormGroupBosons struct {
	Template string `default:"vertical"`
	Attrs    hanariu.Attrs
}

var formGroupStyles = hanariu.Boson{
	"default":    "formgroup-default",
	"vertical":   "formgroup-vertical",
	"horizontal": "formgroup-horizontal",
}

func FormGroup(props *FormGroupBosons) templ.Component {
	classes := getFormGroupClasses(props.Template)
	return hanariu.CreateComponent("div", classes, props.Attrs, false)
}

func getFormGroupClasses(template string) string {
	temp := hanariu.GetTagDefault("Template", template, FormGroupBosons{})
	return formGroupStyles["default"] + " " + formGroupStyles[temp]
}

var _ = templruntime.GeneratedTemplate
