// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package hanariu

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/Discorder20/raw-h/pkg/hanariu"

type TooltipBosons struct {
	Color     string `default:"white"`
	Id        string `default:"tooltip"`
	Placement string `default:"bottom"`
	Offset    string `default:"10"`
}

var tooltipColorStyles = hanariu.Boson{
	"white":     "tooltip-color-white",
	"primary":   "tooltip-color-primary",
	"secondary": "tooltip-color-secondary",
	"warning":   "tooltip-color-warning",
	"danger":    "tooltip-color-danger",
	"success":   "tooltip-color-success",
	"info":      "tooltip-color-info",
}

func Tooltip(props *TooltipBosons) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"tooltip\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 = []any{"absolute h-2 w-2 rotate-45 " + tooltipColorStyles[hanariu.GetTagDefault("Color", props.Color, TooltipBosons{})]}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var3...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div data-arrow=\"arrow\" class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var3).String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/hanariu/atoms/tooltip.templ`, Line: 1, Col: 0}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\"></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = tooltipContent(props).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func tooltipContent(props *TooltipBosons) templ.Component {
	attrs := make(hanariu.Attrs)

	var bind = "{['data-x-transition:enter']: 'tooltip-transition-enter',['data-x-transition:enter-start']: 'tooltip-transition-enter-start',['data-x-transition:enter-end']: 'tooltip-transition-enter-end',['data-x-transition:leave']: 'tooltip-transition-leave',['data-x-transition:leave-start']: 'tooltip-transition-enter-end',['data-x-transition:leave-end']: 'tooltip-transition-enter-start'"
	bind += "}"
	attrs["data-x-cloak"] = ""
	attrs["data-x-show"] = "open"
	idProp := hanariu.GetTagDefault("Id", props.Id, TooltipBosons{})
	placementProp := hanariu.GetTagDefault("Placement", props.Placement, TooltipBosons{})
	offsetProp := hanariu.GetTagDefault("Offset", props.Offset, TooltipBosons{})

	var anchor = "data-x-anchor." + placementProp + ".offset." + offsetProp
	attrs[anchor] = "$refs." + idProp
	attrs["data-x-bind"] = bind

	class := "tooltip-content "
	class += tooltipColorStyles[hanariu.GetTagDefault("Color", props.Color, TooltipBosons{})]
	return hanariu.CreateComponent("div", class, attrs, false)
}

var _ = templruntime.GeneratedTemplate
